# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print, domains_ready: dict):
    """Apply LSOA crosswalk and aggregate to LAD/Region/England."""
    run_name = ctx.vars["run_name"]
    lsoa_vintage = ctx.vars["lsoa_vintage"]
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    
    output_dir = const.outputs_path / run_name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"aggregate: years {year_start}-{year_end}, target vintage LSOA {lsoa_vintage}")
    
    # TODO: Implement aggregation
    # - Load domain CSVs from pipeline store
    # - Apply crosswalk (adi.utils.geo.apply_crosswalk)
    # - Aggregate to LSOA, LAD, Region, England levels
    # - Save outputs
    
    print(f"aggregate: done, output at {const.rel(output_dir)}")
