# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print):
    """Download and cache all raw data sources."""
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    lsoa_vintage = ctx.vars["lsoa_vintage"]
    
    print(f"fetch_data: years {year_start}-{year_end}, target vintage LSOA {lsoa_vintage}")
    
    # TODO: Implement data fetching
    # - Nomis API for claimant counts and populations
    # - data.police.uk archive downloads for crime
    # - NHS Digital scraping for QOF and GP catchment areas
    # - ONS ArcGIS API for boundaries, lookups, and crosswalk data
    
    print("fetch_data: done")
