# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print) -> bool:
    """Download street crime archives from data.police.uk."""
    import zipfile
    from pathlib import Path
    
    import httpx
    
    from adi.utils.scrape import crime_archive_url, download_file
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    
    crime_dir = const.crime_data_path
    crime_dir.mkdir(parents=True, exist_ok=True)
    
    # Each archive covers ~36 months ending at the archive date.
    # The December Y archive covers roughly Jan (Y-2) to Dec Y.
    # So we only need one archive every 3 years for full coverage.
    # We step backward from year_end to ensure the most recent data
    # is always covered, adding archives every 3 years.
    archive_years = set()
    y = year_end
    while y >= year_start:
        archive_years.add(y)
        y -= 3
    # Ensure the earliest year is covered (the archive at y covers [y-2, y],
    # so if year_start > y-2 we might not need it, but it's safe to include)
    if year_start < min(archive_years) - 2:
        archive_years.add(min(archive_years) - 3)
    
    print(f"fetch_crime: need archives for years {sorted(archive_years)}")
    
    for archive_year in sorted(archive_years):
        # Try December of the archive year first, fall back to earlier months
        for month in [12, 6, 1]:
            archive_name = f"{archive_year}-{month:02d}"
            zip_path = crime_dir / f"{archive_name}.zip"
            extract_marker = crime_dir / f".extracted_{archive_name}"
    
            if extract_marker.exists():
                print(f"  {archive_name}: already extracted, skipping")
                break
    
            if zip_path.exists():
                print(f"  {archive_name}: ZIP exists, extracting...")
            else:
                url = crime_archive_url(archive_year, month)
                # Check if the archive exists
                async with httpx.AsyncClient(timeout=30, follow_redirects=True) as client:
                    head = await client.head(url)
                if head.status_code != 200:
                    print(f"  {archive_name}: not available (HTTP {head.status_code}), trying next month...")
                    continue
    
                size_mb = int(head.headers.get("content-length", 0)) / 1024 / 1024
                print(f"  {archive_name}: downloading ({size_mb:.0f} MB)...")
                await download_file(url, zip_path, print=print)
    
            # Extract
            print(f"  {archive_name}: extracting...")
            with zipfile.ZipFile(zip_path) as zf:
                zf.extractall(crime_dir)
            extract_marker.touch()
            print(f"  {archive_name}: extracted")
    
            # Remove ZIP to save disk space
            zip_path.unlink()
            break
    
    print("fetch_crime: done")
    return True
