# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print) -> bool:
    """Download LSOA mid-year population estimates from Nomis."""
    from adi.utils.nomis import (
        download_population_bands,
        download_populations,
        latest_population_year,
    )
    import asyncio
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    lsoa_vintage = ctx.vars["lsoa_vintage"]
    
    pop_dir_2021 = const.population_data_path / "lsoa_2021"
    pop_dir_2011 = const.population_data_path / "lsoa_2011"
    band_dir = const.population_data_path / "lsoa_age_bands"
    
    tasks = []
    
    # LSOA 2021 populations (NM_2014_1) are the published denominator for every rate.
    #
    # The series is always about a year behind the claimant and crime data, because
    # ONS releases LSOA mid-year estimates roughly 14 months in arrears: today it ends
    # at 2024 while the ADI publishes 2025. `beyond_series="substitute"` is the ADI's
    # standing answer -- carry the last published estimate forward for that one year,
    # say so in the log, and leave the rows' DATE_NAME stating the year they really
    # hold. It refuses a second year of it.
    #
    # What it is NOT is a silent fallback. Nomis answers an out-of-range `date` with
    # its newest estimate and HTTP 200, so before this the node asked for 2025, was
    # handed 2024, and wrote it to population_2025.csv with nothing anywhere
    # recording the substitution (#16).
    print(f"fetch_populations: LSOA 2021, years {year_start}-{year_end}")
    tasks.append(download_populations(
        pop_dir_2021, year_start, year_end,
        geography_type="TYPE151", beyond_series="substitute", print=print,
    ))
    
    # LSOA 2011 populations (NM_2010_1) are needed by the domain processors, whose
    # sources only report LSOA 2011 codes. This series ended in 2020 and will not be
    # extended, so later years are skipped rather than substituted: process_* handles
    # them explicitly, and copying 2020 forward here would silently pre-empt that.
    # `year_start` is clamped down so the last published year is always on disk for
    # them to fall back to, whatever range this run asks for.
    lsoa2011_latest = await latest_population_year("TYPE298", print=print)
    lsoa2011_start = min(year_start, lsoa2011_latest)
    print(f"fetch_populations: LSOA 2011, years {lsoa2011_start}-{year_end} "
          f"(series ends {lsoa2011_latest})")
    tasks.append(download_populations(
        pop_dir_2011, lsoa2011_start, year_end,
        geography_type="TYPE298", beyond_series="skip", print=print,
    ))
    
    # The same two series again, split into the age bands QOF measures prevalence
    # against (asthma 6+, rheumatoid arthritis 16+, diabetes 17+, chronic kidney
    # disease / depression / epilepsy / non-diabetic hyperglycaemia / obesity 18+,
    # osteoporosis 50+). The ADI divides every condition by the all-ages list, which
    # both misstates the level -- osteoporosis 0.450% against NHS England's published
    # 1.198% -- and, because deprived neighbourhoods are child-heavy, deflates
    # deprived areas more than affluent ones, flattening the index's own health
    # deprivation gradient (#42).
    #
    # One changed query parameter on datasets already in use, so coverage is
    # identical to the all-ages population above and the same beyond-series policies
    # apply for the same reasons: 2025 stands on the mid-2024 LSOA 2021 estimate, and
    # the LSOA 2011 series simply stops at 2020. Both vintages are needed -- LSOA 2021
    # is the published denominator, LSOA 2011 weights the crosswalk's merge rows.
    #
    # ~6.6 MB per year, 18 years, so this dominates the node on a cold run and costs
    # nothing on a warm one: existing files are re-validated, never re-downloaded.
    print(f"fetch_populations: QOF age bands, LSOA 2021 {year_start}-{year_end}")
    tasks.append(download_population_bands(
        band_dir, year_start, year_end,
        geography_type="TYPE151", beyond_series="substitute", print=print,
    ))
    print(f"fetch_populations: QOF age bands, LSOA 2011 {lsoa2011_start}-{year_end}")
    tasks.append(download_population_bands(
        band_dir, lsoa2011_start, year_end,
        geography_type="TYPE298", beyond_series="skip", print=print,
    ))
    
    await asyncio.gather(*tasks)
    print("fetch_populations: done")
    return True
