# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print) -> bool:
    """Download LSOA mid-year population estimates from Nomis."""
    from adi.utils.nomis import download_populations
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    lsoa_vintage = ctx.vars["lsoa_vintage"]
    
    geography_type = "TYPE151" if lsoa_vintage == "2021" else "TYPE298"
    
    print(f"fetch_populations: years {year_start}-{year_end}, LSOA {lsoa_vintage} ({geography_type})")
    await download_populations(
        const.population_data_path,
        year_start,
        year_end,
        geography_type=geography_type,
        print=print,
    )
    print("fetch_populations: done")
    return True
