# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print) -> bool:
    """Download Universal Credit claimant count data from Nomis."""
    from adi.utils.nomis import download_claimant_counts
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    
    # Claimant count data starts at 2013.
    # Historical data is only available at LSOA 2011 (TYPE298).
    # The crosswalk in the aggregate node handles conversion to LSOA 2021.
    effective_start = max(year_start, 2013)
    
    print(f"fetch_claimant_counts: years {effective_start}-{year_end}, LSOA 2011 (TYPE298)")
    await download_claimant_counts(
        const.claimant_data_path,
        effective_start,
        year_end,
        geography_type="TYPE298",
        print=print,
    )
    print("fetch_claimant_counts: done")
    return True
