# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print) -> bool:
    """Download LSOA boundaries, lookups, and crosswalk data from ONS."""
    from adi.utils.ons import download_geo_data
    lsoa_vintage = ctx.vars["lsoa_vintage"]
    
    print(f"fetch_geo: downloading geographic data for LSOA {lsoa_vintage}...")
    await download_geo_data(const.inputs_path, lsoa_vintage, print=print)
    print("fetch_geo: done")
    return True
