# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print, data_ready: dict) -> bool:
    """Process raw claimant count data into per-LSOA annual rates."""
    year_start = ctx.vars["year_start"]
    year_end = ctx.vars["year_end"]
    run_name = ctx.vars["run_name"]
    
    output_dir = const.pipeline_store_path / run_name / "claimant_counts"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"process_claimant_counts: years {year_start}-{year_end}")
    
    # TODO: Implement claimant count processing
    
    print(f"process_claimant_counts: done, output at {const.rel(output_dir)}")
    return True
