# AUTOGENERATED! DO NOT EDIT!

from adi import const

async def main(ctx, print, outputs_ready) -> bool:
    """Validate the published outputs and record the report."""
    import json
    import subprocess
    import sys
    from collections import Counter
    run_name = ctx.vars["run_name"]
    
    outputs_dir = const.outputs_path / run_name
    report_path = outputs_dir / "validation_report.json"
    script_path = const.repo_root / "scripts" / "validate_outputs.py"
    
    if not outputs_dir.exists():
        raise FileNotFoundError(
            f"No outputs to validate at {const.rel(outputs_dir)}. The aggregate node "
            f"should have written them before this node ran."
        )
    if not script_path.exists():
        raise FileNotFoundError(f"Validator not found at {const.rel(script_path)}.")
    
    print(f"validate: checking {const.rel(outputs_dir)}")
    proc = subprocess.run(
        [sys.executable, str(script_path), "--run", run_name, "--json"],
        capture_output=True, text=True, cwd=str(const.repo_root),
    )
    
    # The validator exits 0 (clean) or 1 (blockers present). Anything else -- 2 for
    # missing outputs, or a traceback -- means the check did not happen, which is not
    # something to shrug off and continue from.
    if proc.returncode not in (0, 1):
        raise RuntimeError(
            f"validate_outputs.py exited {proc.returncode} without completing.\n"
            f"stderr:\n{proc.stderr.strip()}"
        )
    try:
        report = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"validate_outputs.py produced output that is not the JSON report: {exc}\n"
            f"stdout starts: {proc.stdout[:400]!r}\nstderr:\n{proc.stderr.strip()}"
        ) from exc
    
    findings = report["findings"]
    report_path.write_text(json.dumps(report, indent=2, default=str))
    print(f"  report written to {const.rel(report_path)}")
    counts = Counter(f["severity"] for f in findings)
    print(f"  {counts.get('BLOCKER', 0)} BLOCKER, {counts.get('WARN', 0)} WARN, "
          f"{counts.get('INFO', 0)} INFO")
    
    structural = [f for f in findings
                  if f["severity"] == "BLOCKER" and "->" in str(f["geography"])]
    source_blockers = [f for f in findings
                       if f["severity"] == "BLOCKER" and "->" not in str(f["geography"])]
    
    # Print every blocker. A finding nobody reads is not a check, and this is the
    # only place the whole picture is put in front of whoever ran the pipeline.
    for f in source_blockers:
        print(f"    BLOCKER {f['domain']}/{f['metric']} {f['geography']} "
              f"{f['year']}: {f['reason']}")
    if source_blockers:
        print(f"  {len(source_blockers)} source-data blocker(s) above. The pipeline "
              f"reproduces its sources faithfully; correcting these is build_data.py's "
              f"job. Not failing the run on them.")
    
    if structural:
        for f in structural:
            print(f"    STRUCTURAL {f['domain']}/{f['metric']} {f['geography']} "
                  f"{f['year']}: {f['reason']} (value={f['value']}, {f['neighbours']})")
        raise ValueError(
            f"{len(structural)} structural blocker(s): the published levels do not "
            f"reconcile with each other. Only a bug in this pipeline can produce that, "
            f"so the run is failed rather than published. Full report at "
            f"{const.rel(report_path)}."
        )
    
    print(f"validate: done, no structural blockers")
    return True
